name = "docbuild"
version = "0.1.0"
reservoir = false
packagesDir = "../.lake/packages"

[[require]]
name = "TauLib"
path = "../"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.28.0-rc1"
