import TauLib.BookIII.Bridge.G8ActualXiZetaNoGhostDecomposition
import TauLib.BookIII.Bridge.G8CanonicalActualOrthodoxCenteredChartSelector

/-!
# TauLib.BookIII.Bridge.G8ActualXiZetaCanonicalPreimageRealization

Canonical tau-preimage realization for the actual Mathlib-backed `xi` chart.

This module instantiates the actual `xi`/`zeta` source with the canonical
tau boundary-witness carrier.  It proves the current pointwise no-ghost
contract:

* actual off-axis `xi` shadow;
* selected canonical tau boundary witness;
* normalized-axis relation;
* tau critical imbalance.

This closes the present formal pointwise witness contract for the canonical
carrier.  It does not prove O3, analytic-completion uniqueness, full divisor
transfer, tau purity, or the final RH target.
-/

set_option autoImplicit false

noncomputable section

namespace Tau.BookIII.Bridge

open Tau.BookIII.Spectral

-- ============================================================
-- CANONICAL ACTUAL XI/ZETA SOURCE
-- ============================================================

/-- Source data for the actual `xi` chart with the tau side fixed to the
    canonical boundary-witness carrier. -/
structure G8ActualXiZetaCanonicalPreimageSource where
  transfer : G8dZeroDivisorTransferContext
  g3ZetaChartReadout :
    transfer.completion.chart.g3ZetaBridge
  g4CompletedXiReadout :
    transfer.completion.chart.g4AnalyticContinuation

/-- The canonical actual source as an ordinary actual `xi`/`zeta` source. -/
def g8ActualXiZetaCanonical_to_actualSource
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8ActualXiZetaSourceContext where
  transfer := source.transfer
  tauWitness := G8CanonicalTauWitnessCarrier
  tauNormalForm := fun w => w.down.nf
  g3ZetaChartReadout := source.g3ZetaChartReadout
  g4CompletedXiReadout := source.g4CompletedXiReadout
  status := .conditionalExclusionAvailable

/-- The canonical actual source as a canonical tau-witness source. -/
def g8ActualXiZetaCanonical_to_canonicalSource
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8CanonicalTauWitnessSource where
  transfer := source.transfer
  orthodoxZero := OrthodoxXiZeroCarrier
  isOrthodoxOffCriticalZero := OrthodoxXiCarrierOffCritical
  centeredShadow := orthodoxXiCarrierCenteredShadow
  offCritical_iff_notShadowAxis := by
    intro z
    exact orthodoxXiCarrierOffCritical_iff_notOnAxis z
  g3ZetaChartReadout := source.g3ZetaChartReadout
  g4CompletedXiReadout := source.g4CompletedXiReadout
  status := .conditionalInterface

/-- The actual source generated by a canonical actual source uses the canonical
    tau-witness carrier. -/
theorem g8ActualXiZetaCanonical_actual_tauWitness_eq
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    (g8ActualXiZeta_base
      (g8ActualXiZetaCanonical_to_actualSource source)).tauWitness =
      G8CanonicalTauWitnessCarrier :=
  rfl

-- ============================================================
-- CHART ALIGNMENT
-- ============================================================

/-- The actual and canonical centered charts have the same off-axis predicate
    on the shared actual `xi` carrier. -/
theorem g8ActualXiZetaCanonical_actualOffAxis_to_canonicalOffAxis
    (source : G8ActualXiZetaCanonicalPreimageSource)
    (z : OrthodoxXiZeroCarrier)
    (hOffAxis :
      G8ChartOffAxis
        (g8ActualXiZeta_chart
          (g8ActualXiZetaCanonical_to_actualSource source)) z) :
    G8ChartOffAxis
      (g8CanonicalTauWitness_chart
        (g8ActualXiZetaCanonical_to_canonicalSource source)) z := by
  change ShadowOffAxis (orthodoxXiCarrierCenteredShadow z)
  change ShadowOffAxis (orthodoxXiCarrierCenteredShadow z) at hOffAxis
  exact hOffAxis

/-- The canonical selected witness's normalized relation is also the actual
    source's normalized relation. -/
theorem g8ActualXiZetaCanonical_selectedWitness_actualRelated
    (source : G8ActualXiZetaCanonicalPreimageSource)
    (z : OrthodoxXiZeroCarrier)
    (hOffAxis :
      G8ChartOffAxis
        (g8ActualXiZeta_chart
          (g8ActualXiZetaCanonical_to_actualSource source)) z) :
    G8OrthodoxTauNormalizedAxisRelated
      (g8ActualXiZeta_shadowAxisSource
        (g8ActualXiZetaCanonical_to_actualSource source))
      z
      (g8CanonicalTauWitnessForOffAxis
        (g8ActualXiZetaCanonical_to_canonicalSource source)
        z
        (g8ActualXiZetaCanonical_actualOffAxis_to_canonicalOffAxis
          source z hOffAxis)) := by
  have hRel :=
    g8CanonicalTauWitnessForOffAxis_normalizedRelated
      (g8ActualXiZetaCanonical_to_canonicalSource source)
      z
      (g8ActualXiZetaCanonical_actualOffAxis_to_canonicalOffAxis
        source z hOffAxis)
  simpa [
    g8ActualXiZetaCanonical_to_actualSource,
    g8ActualXiZetaCanonical_to_canonicalSource,
    g8ActualXiZeta_shadowAxisSource,
    g8CanonicalTauWitness_shadowAxisSource
  ] using hRel

/-- The canonical selected witness carries tau critical imbalance in the actual
    source's tau-normal-form map. -/
theorem g8ActualXiZetaCanonical_selectedWitness_tauCritical
    (source : G8ActualXiZetaCanonicalPreimageSource)
    (z : OrthodoxXiZeroCarrier)
    (hOffAxis :
      G8ChartOffAxis
        (g8ActualXiZeta_chart
          (g8ActualXiZetaCanonical_to_actualSource source)) z) :
    TauCriticalImbalance
      ((g8ActualXiZetaCanonical_to_actualSource source).tauNormalForm
        (g8CanonicalTauWitnessForOffAxis
          (g8ActualXiZetaCanonical_to_canonicalSource source)
          z
          (g8ActualXiZetaCanonical_actualOffAxis_to_canonicalOffAxis
            source z hOffAxis))) := by
  have hCrit :=
    g8CanonicalTauWitnessForOffAxis_criticalImbalance
      (g8ActualXiZetaCanonical_to_canonicalSource source)
      z
      (g8ActualXiZetaCanonical_actualOffAxis_to_canonicalOffAxis
        source z hOffAxis)
  simpa [
    g8ActualXiZetaCanonical_to_actualSource,
    g8ActualXiZetaCanonical_to_canonicalSource,
    g8CanonicalTauWitness_test
  ] using hCrit

-- ============================================================
-- POINTWISE PREIMAGE CONTRACT
-- ============================================================

/-- The canonical actual source satisfies the pointwise actual no-ghost
    preimage contract. -/
theorem g8ActualXiZetaCanonical_pointwisePreimages
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8ActualXiZetaPointwiseTauImbalancePreimagesExist
      (g8ActualXiZetaCanonical_to_actualSource source) := by
  intro z hOffAxis
  let hCanonOffAxis :=
    g8ActualXiZetaCanonical_actualOffAxis_to_canonicalOffAxis
      source z hOffAxis
  let w :=
    g8CanonicalTauWitnessForOffAxis
      (g8ActualXiZetaCanonical_to_canonicalSource source)
      z hCanonOffAxis
  exact
    ⟨w,
      ⟨g8ActualXiZetaCanonical_selectedWitness_actualRelated
          source z hOffAxis,
        g8ActualXiZetaCanonical_selectedWitness_tauCritical
          source z hOffAxis⟩⟩

/-- The canonical actual source realizes tau critical imbalance as the local
    tau off-critical witness predicate. -/
theorem g8ActualXiZetaCanonical_tauWitnessRealization
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8OffAxisTauWitnessRealization
      (g8ActualXiZeta_chart
        (g8ActualXiZetaCanonical_to_actualSource source)) := by
  intro _w hImbalance
  exact hImbalance

/-- The canonical actual source supplies the pointwise no-ghost decomposition. -/
def g8ActualXiZetaCanonical_to_noGhostDecomposition
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8ActualXiZetaNoGhostDecomposition
      (g8ActualXiZetaCanonical_to_actualSource source) where
  pointwisePreimages :=
    g8ActualXiZetaCanonical_pointwisePreimages source
  tauWitness :=
    g8ActualXiZetaCanonical_tauWitnessRealization source

/-- The canonical actual source supplies the existing actual `xi`/`zeta`
    corridor. -/
def g8ActualXiZetaCanonical_to_corridor
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8ActualXiZetaCorridor
      (g8ActualXiZetaCanonical_to_actualSource source) :=
  g8ActualXiZetaNoGhostDecomposition_to_corridor
    (g8ActualXiZetaCanonical_to_noGhostDecomposition source)

/-- The canonical actual source yields the local one-sided pullback. -/
theorem g8ActualXiZetaCanonical_yields_pullback
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    G8eOffCriticalPullback
      (g8ActualXiZeta_base
        (g8ActualXiZetaCanonical_to_actualSource source)) :=
  g8ActualXiZetaNoGhostDecomposition_yields_pullback
    (g8ActualXiZetaCanonical_to_actualSource source)
    (g8ActualXiZetaCanonical_to_noGhostDecomposition source)

/-- The canonical actual source plus tau-side purity yields local exclusion of
    off-critical actual `xi` zeros. -/
theorem g8ActualXiZetaCanonical_noOffCriticalXiZeros
    (source : G8ActualXiZetaCanonicalPreimageSource)
    (tauPurity :
      G8eTauPurityExcludesOffCritical
        (g8ActualXiZeta_base
          (g8ActualXiZetaCanonical_to_actualSource source))) :
    G8eNoOrthodoxOffCriticalZeros
      (g8ActualXiZeta_base
        (g8ActualXiZetaCanonical_to_actualSource source)) :=
  g8ActualXiZetaNoGhostDecomposition_noOffCriticalXiZeros
    (g8ActualXiZetaCanonical_to_actualSource source)
    (g8ActualXiZetaCanonical_to_noGhostDecomposition source)
    tauPurity

-- ============================================================
-- FUTURE STRICT GEOMETRY TARGET
-- ============================================================

/-- Stricter downstream target: replace the binary/sample selected normal-form
    realization with a point-specific tau-geometric witness source.

This is intentionally only a named target.  The present module proves the
current canonical-carrier contract; it does not claim that the stronger
point-specific geometry has been constructed. -/
structure G8ActualXiZetaStrictPointGeometryTarget
    (source : G8ActualXiZetaSourceContext) where
  pointSpecificWitness :
    ∀ z : OrthodoxXiZeroCarrier,
      G8ChartOffAxis (g8ActualXiZeta_chart source) z →
        source.tauWitness
  normalizedRelated :
    ∀ (z : OrthodoxXiZeroCarrier)
      (hOffAxis : G8ChartOffAxis (g8ActualXiZeta_chart source) z),
      G8OrthodoxTauNormalizedAxisRelated
        (g8ActualXiZeta_shadowAxisSource source)
        z
        (pointSpecificWitness z hOffAxis)
  criticalImbalance :
    ∀ (z : OrthodoxXiZeroCarrier)
      (hOffAxis : G8ChartOffAxis (g8ActualXiZeta_chart source) z),
      TauCriticalImbalance
        (source.tauNormalForm (pointSpecificWitness z hOffAxis))
  nonSampleGeometryDiscipline : Prop

-- ============================================================
-- GUARDRAILS
-- ============================================================

/-- The canonical actual no-ghost decomposition remains finite-only at G8b. -/
theorem g8ActualXiZetaCanonical_finiteOnly
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    finiteG8bContext.finiteOnly :=
  g8ActualXiZetaNoGhostDecomposition_finiteOnly
    (g8ActualXiZetaCanonical_to_noGhostDecomposition source)

/-- The canonical actual no-ghost decomposition carries no `xi` divisor claim
    from finite stages. -/
theorem g8ActualXiZetaCanonical_noXiDivisorClaim
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    finiteG8bContext.noXiDivisorClaim :=
  g8ActualXiZetaNoGhostDecomposition_noXiDivisorClaim
    (g8ActualXiZetaCanonical_to_noGhostDecomposition source)

/-- The canonical actual no-ghost decomposition carries no analytic-completion
    claim from finite stages. -/
theorem g8ActualXiZetaCanonical_noAnalyticCompletionClaim
    (source : G8ActualXiZetaCanonicalPreimageSource) :
    finiteG8bContext.noAnalyticCompletionClaim :=
  g8ActualXiZetaNoGhostDecomposition_noAnalyticCompletionClaim
    (g8ActualXiZetaCanonical_to_noGhostDecomposition source)

end Tau.BookIII.Bridge
