import TauLib.BookIII.Bridge.G8BookIIICh23CauchyTauCirclePeriodProofStones

/-!
# TauLib.BookIII.Bridge.G8BookIIICh23CauchyTauCircleRightInverseReduction

Right-inverse reduction for the A1.1 floor-lift period corridor.

The theorem-backed unit-period left inverse already shows that every
floor-lifted `UnitAddCircle` point reads back to the original additive-circle
period.  The global right inverse is a different statement: every
Cauchy-parametrized canonical tau-circle point must be represented by the
floor-normalized lift of its unit-period readout.

This module closes the generated-image right inverse and proves that the
global right inverse is exactly image-surjectivity of the floor lift.  It also
isolates the stronger period-canonical compatibility statement that would
identify an arbitrary Cauchy angle with its floor-normalized representative.
-/

set_option autoImplicit false

namespace Tau.BookIII.Bridge

open Tau.Boundary

-- ============================================================
-- FLOOR-LIFT IMAGE POINTS
-- ============================================================

/-- The Cauchy-parametrized canonical tau-circle point generated by the
    theorem-backed floor lift of a `UnitAddCircle` period. -/
noncomputable def g8BookIIICh23FloorLiftCauchyPoint
    (u : UnitAddCircle) :
    TauCircleCauchyParametrizedCanonicalPoint :=
  TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle
    (g8BookIIICh23RealIcoFloorLiftSource
      |>.toBoundedAngleOfUnitAddCircle u)
    (g8BookIIICh23RealIcoFloorLiftSource
      |>.toBoundedAngleOfUnitAddCircle_cauchy u)

/-- Generated floor-lift points read back to their original unit period. -/
theorem g8BookIIICh23FloorLiftCauchyPoint_unitPeriod
    (u : UnitAddCircle) :
    g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod
        (g8BookIIICh23RealIcoFloorLiftSource
          |>.toBoundedAngleOfUnitAddCircle u)
        (g8BookIIICh23RealIcoFloorLiftSource
          |>.toBoundedAngleOfUnitAddCircle_cauchy u) =
      u :=
  g8BookIIICh23RealIcoFloorLift_unitPeriod_left_inv u

/-- Any readout that agrees with the unit-period readout is a right inverse on
    generated floor-lift points. -/
theorem g8BookIIICh23FloorLiftCanonicalRightInverse_generated
    (fromCauchyParametrized :
      TauCircleCauchyParametrizedCanonicalPoint → UnitAddCircle)
    (hagrees :
      ∀ (a : BoundedTauAngle) (ha : BoundedTauAngle.IsCauchy a),
        fromCauchyParametrized
            (TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle
              a ha) =
          g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod a ha)
    (u : UnitAddCircle) :
    g8BookIIICh23FloorLiftCauchyPoint
        (fromCauchyParametrized
          (g8BookIIICh23FloorLiftCauchyPoint u)) =
      g8BookIIICh23FloorLiftCauchyPoint u := by
  dsimp [g8BookIIICh23FloorLiftCauchyPoint]
  rw [hagrees]
  rw [g8BookIIICh23RealIcoFloorLift_unitPeriod_left_inv]

-- ============================================================
-- RIGHT INVERSE AS IMAGE SURJECTIVITY
-- ============================================================

/-- The exact image-surjectivity statement behind the global floor-lift right
    inverse: every Cauchy-parametrized canonical point is generated by a
    floor-lifted additive-circle period. -/
def G8BookIIICh23FloorLiftCauchyImageSurjectivity : Prop :=
  ∀ p : TauCircleCauchyParametrizedCanonicalPoint,
    ∃ u : UnitAddCircle, g8BookIIICh23FloorLiftCauchyPoint u = p

/-- A global right inverse immediately gives image-surjectivity. -/
theorem g8BookIIICh23FloorLift_imageSurjective_of_rightInverse
    {fromCauchyParametrized :
      TauCircleCauchyParametrizedCanonicalPoint → UnitAddCircle}
    (h :
      G8BookIIICh23FloorLiftCanonicalRightInverseFor
        fromCauchyParametrized) :
    G8BookIIICh23FloorLiftCauchyImageSurjectivity := by
  intro p
  exact ⟨fromCauchyParametrized p, h p⟩

/-- A choice of image preimage supplied by image-surjectivity. -/
noncomputable def g8BookIIICh23FloorLiftReadoutOfImageSurjectivity
    (h : G8BookIIICh23FloorLiftCauchyImageSurjectivity)
    (p : TauCircleCauchyParametrizedCanonicalPoint) : UnitAddCircle :=
  Classical.choose (h p)

/-- Image-surjectivity supplies a global right inverse by choosing a
    floor-lift preimage for each Cauchy-parametrized canonical point. -/
theorem g8BookIIICh23FloorLift_rightInverse_of_imageSurjectivity
    (h : G8BookIIICh23FloorLiftCauchyImageSurjectivity) :
    G8BookIIICh23FloorLiftCanonicalRightInverseFor
      (g8BookIIICh23FloorLiftReadoutOfImageSurjectivity h) := by
  intro p
  exact Classical.choose_spec (h p)

/-- The global floor-lift right inverse is exactly image-surjectivity of the
    generated floor-lift lobe. -/
theorem g8BookIIICh23FloorLift_rightInverse_iff_imageSurjectivity :
    (∃ fromCauchyParametrized :
        TauCircleCauchyParametrizedCanonicalPoint → UnitAddCircle,
        G8BookIIICh23FloorLiftCanonicalRightInverseFor
          fromCauchyParametrized) ↔
      G8BookIIICh23FloorLiftCauchyImageSurjectivity := by
  constructor
  · rintro ⟨fromCauchyParametrized, hright⟩
    exact
      g8BookIIICh23FloorLift_imageSurjective_of_rightInverse
        hright
  · intro hsurj
    exact
      ⟨g8BookIIICh23FloorLiftReadoutOfImageSurjectivity hsurj,
        g8BookIIICh23FloorLift_rightInverse_of_imageSurjectivity
          hsurj⟩

-- ============================================================
-- PERIOD-CANONICAL COMPATIBILITY
-- ============================================================

/-- Period-canonical compatibility for the current exact-angle quotient:
    replacing a Cauchy bounded angle by the floor-normalized representative of
    its unit period preserves the Cauchy-parametrized canonical point. -/
def G8BookIIICh23FloorLiftPeriodCanonicalCompatibility : Prop :=
  ∀ (a : BoundedTauAngle) (ha : BoundedTauAngle.IsCauchy a),
    TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle
        (g8BookIIICh23RealIcoFloorLiftSource
          |>.toBoundedAngleOfUnitAddCircle
            (g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod a ha))
        (g8BookIIICh23RealIcoFloorLiftSource
          |>.toBoundedAngleOfUnitAddCircle_cauchy
            (g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod a ha)) =
      TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle a ha

/-- Period-canonical compatibility implies image-surjectivity, using the
    existing representative carried by each Cauchy-parametrized point. -/
theorem g8BookIIICh23FloorLift_imageSurjective_of_periodCanonicalCompatibility
    (hcompat : G8BookIIICh23FloorLiftPeriodCanonicalCompatibility) :
    G8BookIIICh23FloorLiftCauchyImageSurjectivity := by
  intro p
  rcases p.2 with ⟨a, ha, hp⟩
  refine
    ⟨g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod a ha, ?_⟩
  exact (hcompat a ha).trans (Subtype.ext hp)

/-- Period-canonical compatibility is sufficient for the global right inverse. -/
theorem g8BookIIICh23FloorLift_rightInverse_of_periodCanonicalCompatibility
    (hcompat : G8BookIIICh23FloorLiftPeriodCanonicalCompatibility) :
    ∃ fromCauchyParametrized :
        TauCircleCauchyParametrizedCanonicalPoint → UnitAddCircle,
      G8BookIIICh23FloorLiftCanonicalRightInverseFor
        fromCauchyParametrized :=
  g8BookIIICh23FloorLift_rightInverse_iff_imageSurjectivity.mpr
    (g8BookIIICh23FloorLift_imageSurjective_of_periodCanonicalCompatibility
      hcompat)

/-- A readout source forces period-canonical compatibility.  This records the
    exact content carried by the `right_inv` field together with agreement
    with the quotient-real unit-period readout. -/
theorem g8BookIIICh23FloorLift_periodCanonicalCompatibility_of_readout
    (source :
      G8BookIIICh23FloorLiftCauchyPeriodReadoutSource) :
    G8BookIIICh23FloorLiftPeriodCanonicalCompatibility := by
  intro a ha
  simpa [source.agreesWithUnitPeriod a ha] using
    source.right_inv
      (TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle a ha)

-- ============================================================
-- GUARDRAILS AND FALSIFIERS
-- ============================================================

/-- Falsifier surface: a Cauchy-parametrized canonical point outside the
    generated floor-lift image blocks any global right inverse. -/
structure G8BookIIICh23FloorLiftPointOutsideImage where
  point : TauCircleCauchyParametrizedCanonicalPoint
  notInImage :
    ¬ ∃ u : UnitAddCircle,
      g8BookIIICh23FloorLiftCauchyPoint u = point

/-- A point outside the floor-lift image refutes image-surjectivity. -/
theorem G8BookIIICh23FloorLiftPointOutsideImage.refutesImageSurjectivity
    (gap : G8BookIIICh23FloorLiftPointOutsideImage) :
    ¬ G8BookIIICh23FloorLiftCauchyImageSurjectivity := by
  intro hsurj
  exact gap.notInImage (hsurj gap.point)

/-- A point outside the floor-lift image refutes every global right inverse. -/
theorem G8BookIIICh23FloorLiftPointOutsideImage.refutesRightInverse
    (gap : G8BookIIICh23FloorLiftPointOutsideImage) :
    ¬ ∃ fromCauchyParametrized :
        TauCircleCauchyParametrizedCanonicalPoint → UnitAddCircle,
        G8BookIIICh23FloorLiftCanonicalRightInverseFor
          fromCauchyParametrized := by
  intro hright
  exact
    gap.refutesImageSurjectivity
      (g8BookIIICh23FloorLift_rightInverse_iff_imageSurjectivity.mp
        hright)

/-- Falsifier surface: a period-normalization mismatch is exactly the
    obstruction to deriving the right inverse from arbitrary Cauchy angles. -/
structure G8BookIIICh23FloorLiftPeriodCanonicalMismatch where
  angle : BoundedTauAngle
  cauchy : BoundedTauAngle.IsCauchy angle
  mismatch :
    TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle
        (g8BookIIICh23RealIcoFloorLiftSource
          |>.toBoundedAngleOfUnitAddCircle
            (g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod
              angle cauchy))
        (g8BookIIICh23RealIcoFloorLiftSource
          |>.toBoundedAngleOfUnitAddCircle_cauchy
            (g8BookIIICh23CauchyBoundedAngleUnitAddCirclePeriod
              angle cauchy)) ≠
      TauCircleCauchyParametrizedCanonicalPoint.ofBoundedAngle
        angle cauchy

/-- A period-normalization mismatch refutes period-canonical compatibility. -/
theorem
    G8BookIIICh23FloorLiftPeriodCanonicalMismatch.refutesPeriodCanonicalCompatibility
    (gap : G8BookIIICh23FloorLiftPeriodCanonicalMismatch) :
    ¬ G8BookIIICh23FloorLiftPeriodCanonicalCompatibility := by
  intro hcompat
  exact gap.mismatch (hcompat gap.angle gap.cauchy)

/-- A period-normalization mismatch refutes any readout source whose right
    inverse is claimed through the current exact floor lift. -/
theorem
    G8BookIIICh23FloorLiftPeriodCanonicalMismatch.refutesReadoutSource
    (gap : G8BookIIICh23FloorLiftPeriodCanonicalMismatch)
    (source :
      G8BookIIICh23FloorLiftCauchyPeriodReadoutSource) :
    False :=
  gap.refutesPeriodCanonicalCompatibility
    (g8BookIIICh23FloorLift_periodCanonicalCompatibility_of_readout
      source)

end Tau.BookIII.Bridge
