import TauLib.BookI.Polarity.InverseLimit
import Mathlib.Topology.Bases
import Mathlib.Topology.Constructions

/-!
# TauLib.BookI.Boundary.Bridge.TauProfiniteTopology

**Wave 50 — Mathlib `TopologicalSpace` bridge for the τ-profinite carrier**.

First wave of the topological-substrate Mathlib bridge cluster
(Cluster T1, Waves 50–54), targeting `Profinite` as the apex
(compact + Hausdorff + totally disconnected).

This module:
1. Defines the τ-profinite carrier `TauProfinite` as a thin wrapper over
   the production `OmegaInverseLimit` (Wave 8 inverse-limit machinery).
2. Defines the cylinder basis as a `Set (Set TauProfinite)`.
3. Instantiates Mathlib's `TopologicalSpace TauProfinite` via
   `TopologicalSpace.generateFrom` over the cylinder basis.
4. Proves cylinder open/closed properties at the Prop level.

This is **constructive** — no Markov / Classical reasoning. The
cylinder basis directly mirrors the τ-native cylinder predicates from
`BookII/Domains/Cylinders.lean` (lifted from `Bool` to `Set`).

## Methodology check (Bridge zone discipline)

- Module sits in `Boundary/Bridge/` per the Wave 39 CI policy.
- Uses `Mathlib.Topology.Bases` (filter-based, cardinality-agnostic).
- Wraps `OmegaInverseLimit` as `TauProfinite` to attach Mathlib instances
  cleanly without affecting the existing `OmegaInverseLimit` API.

## Registry Cross-References

- [I.D147] TauProfinite (this module)
- [I.D148] TauProfinite.cylinder, cylinderBasis (this module)
- [I.T-W50-1] TopologicalSpace TauProfinite Instance
- [I.T-W50-2] isOpen_cylinder
- [I.T-W50-3] Wave 50 synthesis
-/

set_option autoImplicit false

namespace Tau.Boundary

open Tau.Polarity Tau.Denotation

-- ============================================================
-- PART 1: TauProfinite carrier — wrapper over OmegaInverseLimit
-- ============================================================

/-- **The τ-profinite carrier**.

    A thin wrapper over `OmegaInverseLimit`. Wrapping ensures Mathlib
    instances (`TopologicalSpace`, `T2Space`, `UniformSpace`,
    `CompactSpace`, ...) attach to `TauProfinite` without touching the
    existing `OmegaInverseLimit` API used elsewhere in TauLib. This is
    the idiomatic Mathlib pattern for instance-attachment vehicles
    (cf. `Multiplicative`, `Additive`, `OrderDual`).

    The carrier is in bijection with `OmegaInverseLimit` via
    `TauProfinite.toLimit` and `TauProfinite.mk`. -/
structure TauProfinite where
  /-- The underlying inverse-limit element. -/
  toLimit : OmegaInverseLimit

namespace TauProfinite

@[ext] theorem ext {x y : TauProfinite} (h : x.toLimit = y.toLimit) : x = y := by
  cases x; cases y; congr

/-- The k-th projection of a TauProfinite element: the residue mod
    `primorial k` at depth `k`. -/
def proj (x : TauProfinite) (k : TauIdx) : TauIdx := x.toLimit.coeff k

theorem proj_def (x : TauProfinite) (k : TauIdx) :
    x.proj k = x.toLimit.coeff k := rfl

/-- Two TauProfinite elements are equal iff all projections agree. -/
theorem ext_proj {x y : TauProfinite}
    (h : ∀ k, x.proj k = y.proj k) : x = y := by
  apply ext
  cases x with
  | mk xL =>
    cases y with
    | mk yL =>
      cases xL with
      | mk xc xcompat =>
        cases yL with
        | mk yc ycompat =>
          have hcoeff : xc = yc := funext (fun k => h k)
          subst hcoeff
          rfl

-- ============================================================
-- PART 2: Cylinder basis
-- ============================================================

/-- **Cylinder at depth k centered at value c**.

    The set of `TauProfinite` elements whose k-th projection equals `c`.
    This corresponds to the cylinder `C_k(center)` from
    `BookII/Domains/Cylinders.lean`, lifted from `Bool`-valued
    `cylinder_mem` to a Prop-level `Set`.

    Note: `c` should typically be a residue mod `primorial k`; if it
    isn't, the cylinder is just the preimage `proj k ⁻¹' {c}`. -/
def cylinder (k c : TauIdx) : Set TauProfinite :=
  { x | x.proj k = c }

@[simp] theorem mem_cylinder (k c : TauIdx) (x : TauProfinite) :
    x ∈ cylinder k c ↔ x.proj k = c := Iff.rfl

/-- **The cylinder basis**: the family of all cylinders, parametrised by
    depth `k` and center value `c`. -/
def cylinderBasis : Set (Set TauProfinite) :=
  { S | ∃ k c : TauIdx, S = cylinder k c }

theorem cylinder_mem_basis (k c : TauIdx) :
    cylinder k c ∈ cylinderBasis :=
  ⟨k, c, rfl⟩

-- ============================================================
-- PART 3: TopologicalSpace via generateFrom
-- ============================================================

/-- **The τ-profinite topology**: generated by the cylinder basis.

    This is the standard inverse-limit topology — the coarsest topology
    making every projection `proj k : TauProfinite → TauIdx` continuous
    when `TauIdx` carries the discrete topology at each depth.

    The cylinder basis matches Book II's `BookII/Domains/Cylinders.lean`
    construction (the `Bool`-valued `cylinder_mem`), now lifted to
    Mathlib's `Set`-valued open-set lattice. -/
instance : TopologicalSpace TauProfinite :=
  TopologicalSpace.generateFrom cylinderBasis

/-- Every cylinder is open. -/
theorem isOpen_cylinder (k c : TauIdx) : IsOpen (cylinder k c) :=
  TopologicalSpace.GenerateOpen.basic _ ⟨k, c, rfl⟩

/-- The whole space (TauProfinite as a Set) is open. -/
theorem isOpen_univ' : IsOpen (Set.univ : Set TauProfinite) :=
  isOpen_univ

/-- Empty set is open. -/
theorem isOpen_empty' : IsOpen (∅ : Set TauProfinite) :=
  isOpen_empty

-- ============================================================
-- PART 4: Cylinders are closed (foundation for clopen / TotallyDisc)
-- ============================================================

/-- **The complement of a cylinder is open**.

    For fixed `k`, the cylinders `cylinder k c` for varying `c` partition
    `TauProfinite` (every point has a unique `proj k` value). So the
    complement of `cylinder k c` is the union of the other cylinders
    `cylinder k c'` for `c' ≠ c` — which is open as a union of opens.

    This proves cylinders are closed (and hence clopen, since they're
    open by `isOpen_cylinder`). -/
theorem isOpen_compl_cylinder (k c : TauIdx) :
    IsOpen ((cylinder k c)ᶜ) := by
  -- (cylinder k c)ᶜ = ⋃ c' ∈ {c' | c' ≠ c}, cylinder k c'
  -- Each cylinder k c' is open; arbitrary union of opens is open.
  have : (cylinder k c)ᶜ = ⋃ c' ∈ ({c' | c' ≠ c} : Set TauIdx), cylinder k c' := by
    ext x
    simp only [Set.mem_compl_iff, mem_cylinder, Set.mem_iUnion, Set.mem_setOf_eq]
    constructor
    · intro h_ne
      exact ⟨x.proj k, h_ne, rfl⟩
    · rintro ⟨c', hc'_ne, hx⟩ heq
      exact hc'_ne (heq ▸ hx).symm
  rw [this]
  refine isOpen_iUnion (fun c' => ?_)
  refine isOpen_iUnion (fun _ => ?_)
  exact isOpen_cylinder k c'

/-- **Every cylinder is closed**. -/
theorem isClosed_cylinder (k c : TauIdx) : IsClosed (cylinder k c) := by
  rw [← isOpen_compl_iff]
  exact isOpen_compl_cylinder k c

/-- **Every cylinder is clopen** — both open and closed. The fundamental
    topological feature of profinite spaces and the foundation for
    `TotallyDisconnectedSpace` (Wave 51). -/
theorem isClopen_cylinder (k c : TauIdx) : IsClopen (cylinder k c) :=
  ⟨isClosed_cylinder k c, isOpen_cylinder k c⟩

-- ============================================================
-- PART 5: Wave 50 synthesis theorem
-- ============================================================
-- (`IsTopologicalBasis` is deferred to a follow-up wave once the
-- cylinder-intersection lemma at deeper depths is in hand. The
-- core open/closed/clopen properties suffice for Waves 51-54.)
--

/-- **Wave 50 synthesis: TauProfinite Topological-Space-Bridge**.

    Five-clause structural significance:
    1. `TauProfinite` carrier exists (wrapper over `OmegaInverseLimit`).
    2. Cylinder basis defined: `cylinderBasis : Set (Set TauProfinite)`.
    3. `TopologicalSpace TauProfinite` instantiated via `generateFrom`.
    4. Cylinders are clopen — the profinite-defining topological feature.
    5. The construction is fully constructive (no Markov / Classical sites).

    Foundation for Wave 51 (T2 + TotallyDisconnected),
    Wave 52 (UniformSpace), Wave 53 (CompactSpace), Wave 54 (Profinite). -/
theorem h8_tauprofinite_topological_bridge_synthesis :
    Nonempty TauProfinite ∧
    Nonempty (TopologicalSpace TauProfinite) ∧
    -- Cylinders are open
    (∀ k c : TauIdx, IsOpen (cylinder k c)) ∧
    -- Cylinders are closed
    (∀ k c : TauIdx, IsClosed (cylinder k c)) ∧
    -- Cylinders are clopen
    (∀ k c : TauIdx, IsClopen (cylinder k c)) :=
  ⟨⟨⟨nat_to_inverse_limit 0⟩⟩,
   ⟨inferInstance⟩,
   isOpen_cylinder,
   isClosed_cylinder,
   isClopen_cylinder⟩

end TauProfinite
end Tau.Boundary
