import TauLib.BookIV.Arena.RefinementTower
import TauLib.BookI.Boundary.Iota

/-!
# TauLib.BookV.Temporal.BaseCircle

The base circle τ¹: the compact profinite temporal substrate generated by
the α-orbit, with proper time, causal ordering, and geodesic duration.

## Registry Cross-References

- [V.D15] Base Circle — `BaseCircle`
- [V.D16] Alpha-Tick — `AlphaTick`
- [V.D17] Proper Time Series — `ProperTimeSeries`
- [V.T08] Physical Time is Derived — `physical_time_derived`
- [V.P03] Temporal Direction — `temporal_direction`
- [V.D18] Causal Ordering — structural (wraps ProtoTime ordering)
- [V.T09] Causal Ordering Structurally Enforced — `causal_ordering_enforced`
- [V.D19] Geodesic Duration — `GeodesicDuration`
- [V.T10] Total Proper Time Finite — `total_proper_time_bounded`

## Mathematical Content

### Base Circle τ¹ [V.D15]

The base circle τ¹ is the compact profinite space generated by the α-orbit.
It is the temporal axis of τ³ = τ¹ ×_f T². Unlike S¹ (which has metric
structure), τ¹ has only:
- Profinite ordering (from refinement tower levels)
- Causal direction (from α-orbit generation direction)
- Accumulated arc length (proper time)

### Alpha-Tick [V.D16]

An alpha-tick Δ_n is the passage from α_n to α_{n+1} in the refinement tower.
Each tick is a single refinement step, the minimal temporal unit. Physical
time emerges as accumulated arc length of the tick sequence.

### Proper Time [V.D17]

Proper time t(n) is the accumulated arc length along the α-orbit up to
depth n. Each tick contributes a decrement proportional to ι_τ^n (deeper
ticks are shorter), making the total finite:

    t_∞ = Σ_n ι_τ^n = ι_τ/(1 − ι_τ) < ∞

### Causal Ordering [V.D18, V.T09]

The ordering α_m < α_n (for m < n) is not postulated but structurally
forced by the refinement tower: deeper levels refine shallower ones,
and refinement is irreversible (structural arrow of time).

## Ground Truth Sources
- Book V Part II (2nd Edition): Temporal Foundation
- Book IV Chapter 3: Refinement Tower
-/

namespace Tau.BookV.Temporal

open Tau.Kernel Tau.Boundary Tau.BookIV.Arena Tau.BookIV.Sectors

-- ============================================================
-- BASE CIRCLE [V.D15]
-- ============================================================

/-- [V.D15] The base circle τ¹: compact profinite space generated by
    the α-orbit. This is the temporal axis of τ³ = τ¹ ×_f T².

    Key properties:
    - Generated by the α-generator (gravity/temporal sector)
    - Profinite: inverse limit of finite quotients
    - Carries causal ordering (from refinement tower directedness)
    - NOT S¹ with metric — profinite ordering only -/
structure BaseCircle where
  /-- The seed generator (must be alpha for temporal). -/
  seed : Generator
  /-- Seed is alpha. -/
  seed_is_alpha : seed = .alpha
  /-- Reference to the profinite limit structure. -/
  profinite : ProfiniteLimit
  /-- Profinite limit uses the same seed. -/
  seed_consistent : profinite.seed = seed

/-- The canonical base circle from the α-orbit. -/
def canonical_base_circle : BaseCircle where
  seed := .alpha
  seed_is_alpha := rfl
  profinite := alpha_profinite
  seed_consistent := rfl

-- ============================================================
-- ALPHA-TICK [V.D16]
-- ============================================================

/-- [V.D16] Alpha-tick: the minimal temporal passage from depth n to
    depth n+1 in the refinement tower.

    Δ_n := (α_n → α_{n+1})

    Each tick is a single irreversible refinement step. The source
    depth must be strictly less than the target depth. -/
structure AlphaTick where
  /-- Source proto-time (earlier). -/
  source : ProtoTime
  /-- Target proto-time (later). -/
  target : ProtoTime
  /-- Target is exactly one step after source. -/
  consecutive : target.tick = source.tick + 1
  deriving Repr

/-- Construct an alpha-tick from a depth n (tick n → tick n+1). -/
def alpha_tick_at (n : Nat) (hn : n > 0) : AlphaTick where
  source := ⟨n, hn⟩
  target := ⟨n + 1, by omega⟩
  consecutive := rfl

/-- Alpha-ticks preserve the causal direction (source < target). -/
theorem alpha_tick_causal (t : AlphaTick) :
    t.source.tick < t.target.tick := by
  rw [t.consecutive]; omega

-- ============================================================
-- PROPER TIME SERIES [V.D17]
-- ============================================================

/-- [V.D17] Proper time series: accumulated arc length along the α-orbit.

    Each tick contributes a decrement proportional to the depth:
    the deeper the tick, the shorter the time increment. At the
    rational-approximation level, tick n contributes ι_τ^n.

    The total proper time is finite: Σ ι_τ^n = ι_τ/(1−ι_τ) < ∞.

    We store the accumulated time as a Nat pair (numer, denom). -/
structure ProperTimeSeries where
  /-- Current depth (how many ticks accumulated). -/
  depth : Nat
  /-- Depth is positive (at least one tick). -/
  depth_pos : depth > 0
  /-- Accumulated proper time numerator. -/
  time_numer : Nat
  /-- Accumulated proper time denominator. -/
  time_denom : Nat
  /-- Denominator is positive. -/
  denom_pos : time_denom > 0
  deriving Repr

/-- Proper time as Float. -/
def ProperTimeSeries.toFloat (t : ProperTimeSeries) : Float :=
  Float.ofNat t.time_numer / Float.ofNat t.time_denom

-- ============================================================
-- PHYSICAL TIME IS DERIVED [V.T08]
-- ============================================================

/-- [V.T08] Physical time is a DERIVED quantity: it emerges from the
    refinement tower ordering and accumulated arc length, NOT from
    a postulated spacetime manifold.

    The derivation path:
    1. α-orbit generates refinement tower levels
    2. Tower levels carry structural ordering (earlier < later)
    3. Each tick contributes proper-time increment
    4. Accumulated arc length = physical time

    This theorem records that the ProtoTime ordering precedes and
    generates the proper time series. -/
theorem physical_time_derived :
    -- ProtoTime exists before proper time
    (∃ t : ProtoTime, t.tick > 0) ∧
    -- NNO (natural numbers) from alpha-orbit
    (∀ n : Nat, ∃ t : ProtoTime, prototime_to_nat t = n) := by
  constructor
  · exact ⟨⟨1, by omega⟩, by decide⟩
  · exact nno_from_alpha

-- ============================================================
-- TEMPORAL DIRECTION [V.P03]
-- ============================================================

/-- [V.P03] Temporal direction: the generative direction of the α-orbit
    defines the arrow of time. Deeper refinement levels are "later."

    The alpha generator uniquely determines this direction:
    - seed = .alpha (gravity/temporal sector)
    - Profinite limit is directed (from structural arrow)
    - Direction is irreversible (from tower monotonicity) -/
theorem temporal_direction :
    canonical_base_circle.seed = .alpha ∧
    canonical_base_circle.profinite.seed = .alpha := by
  exact ⟨rfl, rfl⟩

-- ============================================================
-- CAUSAL ORDERING [V.D18, V.T09]
-- ============================================================

-- [V.D18] Causal ordering: α_m < α_n means depth m precedes depth n.
-- This is the ProtoTime ordering from Book IV's refinement tower.
-- The ordering is:
-- - Irreflexive (no time tick precedes itself)
-- - Transitive (if a < b and b < c then a < c)
-- - Trichotomous on ticks (= < or >)

/-- [V.T09] Causal ordering is structurally enforced: no axiom needed.
    Wraps structural_arrow from RefinementTower with Book V interpretation.

    The structural arrow of time is built into the refinement tower —
    it is not an additional postulate but a consequence of tower directedness. -/
theorem causal_ordering_enforced (t1 t2 : ProtoTime) (h : t1 < t2) :
    t2.tick > t1.tick :=
  structural_arrow t1 t2 h

/-- Causal ordering is transitive. -/
theorem causal_transitive (t1 t2 t3 : ProtoTime)
    (h12 : t1 < t2) (h23 : t2 < t3) : t1 < t3 :=
  arrow_transitive t1 t2 t3 h12 h23

/-- Causal ordering is irreflexive. -/
theorem causal_irreflexive (t : ProtoTime) : ¬(t < t) :=
  arrow_irreflexive t

-- ============================================================
-- GEODESIC DURATION [V.D19]
-- ============================================================

/-- [V.D19] Geodesic duration between two proto-time events: the
    number of alpha-ticks separating them.

    This is the structural (pre-metric) distance on τ¹. The physical
    proper time requires weighting each tick by the depth-dependent
    arc-length contribution. -/
structure GeodesicDuration where
  /-- Start event. -/
  start : ProtoTime
  /-- End event. -/
  stop : ProtoTime
  /-- End is after start. -/
  causal : start.tick < stop.tick
  deriving Repr

/-- Number of ticks in the geodesic duration. -/
def GeodesicDuration.tick_count (g : GeodesicDuration) : Nat :=
  g.stop.tick - g.start.tick

/-- Tick count is always positive. -/
theorem geodesic_positive (g : GeodesicDuration) :
    g.tick_count > 0 := by
  simp only [GeodesicDuration.tick_count]
  exact Nat.sub_pos_of_lt g.causal

-- ============================================================
-- TOTAL PROPER TIME FINITE [V.T10]
-- ============================================================

/-- [V.T10] Total proper time t_∞ is finite.

    The proper time series is a geometric sum:
    t_∞ = Σ_{n≥1} ι_τ^n = ι_τ/(1−ι_τ) < ∞

    Since ι_τ ≈ 0.341304 < 1, the series converges.
    Limit = ι_τ/(1−ι_τ) ≈ 0.518441.

    We prove the bound: iota < iotaD (i.e. ι_τ < 1), which is
    the convergence condition for the geometric series. -/
theorem total_proper_time_bounded :
    -- ι_τ < 1 (convergence condition)
    iota < iotaD ∧
    -- ι_τ/(1−ι_τ) numerator < denominator (total < 1)
    iota < iotaD - iota := by
  constructor
  · simp [iota, iotaD, iota_tau_numer, iota_tau_denom]
  · simp [iota, iotaD, iota_tau_numer, iota_tau_denom]

-- ============================================================
-- SMOKE TESTS
-- ============================================================

#eval canonical_base_circle.seed                       -- alpha
#eval (alpha_tick_at 1 (by omega)).source.tick         -- 1
#eval (alpha_tick_at 1 (by omega)).target.tick         -- 2
#eval prototime_to_nat ⟨1, by omega⟩                  -- 0
#eval prototime_to_nat ⟨10, by omega⟩                 -- 9

-- Convergence condition: ι_τ < 1
#eval iota < iotaD                                     -- true
-- ι_τ/(1−ι_τ) ≈ 0.518
#eval Float.ofNat iota / Float.ofNat (iotaD - iota)   -- ≈ 0.5184

end Tau.BookV.Temporal
