#!/usr/bin/env python3
"""Apply Panta Rhei shell to doc-gen4 HTML output.

Reads each HTML page in the doc output directory, extracts the <main>
content (doc-gen4's generated documentation), and wraps it in the
Panta Rhei shell template — matching the visual language of
panta-rhei.site while preserving all doc-gen4 content.

The shell template uses placeholders:
  {{TITLE}}        — page title
  {{ROOT}}         — relative path to root (e.g. "../../")
  {{HEAD_EXTRA}}   — extra <head> content from doc-gen4 (scripts, etc.)
  {{NAV_CONTENT}}  — sidebar navigation HTML
  {{MAIN_CONTENT}} — the actual documentation content

Usage:
    python3 apply_shell.py --doc-dir _site --template scripts/shell_template.html
"""

import argparse
import os
import re
from pathlib import Path


# Files to skip (not standalone pages)
SKIP_FILES = {
    "navbar.html",           # iframe source, not a page
    "declaration-data.js",   # data file
    "search.js",             # JavaScript module
    "nav.js",                # JavaScript module
    "color-scheme.js",       # JavaScript module
    "404.html",              # generated by doc-gen4, not needed
}

# Files that are standalone (no left nav)
STANDALONE_FILES = {
    "stats.html",
    "depgraph.html",
    "search.html",
}


def compute_root(filepath: Path, doc_dir: Path) -> str:
    """Compute relative path from a file back to the doc root."""
    rel = filepath.parent.relative_to(doc_dir)
    depth = len(rel.parts)
    if depth == 0:
        return "./"
    return "../" * depth


def extract_title(html: str) -> str:
    """Extract page title from <title> tag or <header><h1>."""
    # Try <title> first
    m = re.search(r'<title>(.*?)</title>', html, re.DOTALL)
    if m:
        title = m.group(1).strip()
        # Remove trailing " - TauLib" or similar
        title = re.sub(r'\s*[-–—]\s*(TauLib|doc-gen4).*$', '', title)
        if title:
            return title

    # Try <header><h1>
    m = re.search(r'<header[^>]*>.*?<h1[^>]*>(.*?)</h1>', html, re.DOTALL)
    if m:
        return re.sub(r'<[^>]+>', '', m.group(1)).strip()

    return "TauLib"


def extract_main(html: str) -> str:
    """Extract content inside <main>...</main>."""
    m = re.search(r'<main[^>]*>(.*?)</main>', html, re.DOTALL)
    if m:
        return m.group(1).strip()

    # Fallback: <div class="main">
    m = re.search(r'<div\s+class="main"[^>]*>(.*?)</div>\s*(?:</body>|$)', html, re.DOTALL)
    if m:
        return m.group(1).strip()

    # Last resort: everything between </header> and </body>
    m = re.search(r'</header>(.*?)</body>', html, re.DOTALL)
    if m:
        return m.group(1).strip()

    return html


def extract_head_extras(html: str) -> str:
    """Extract doc-gen4-specific <head> content (scripts, etc.)."""
    extras = []
    # Find script tags (type="module" for doc-gen4 modules)
    for m in re.finditer(r'<script[^>]*type="module"[^>]*src="([^"]*)"[^>]*></script>', html):
        extras.append(f'<script type="module" src="{m.group(1)}"></script>')
    # Find declaration-data.js
    for m in re.finditer(r'<script[^>]*src="([^"]*declaration-data[^"]*)"[^>]*></script>', html):
        extras.append(f'<script defer src="{m.group(1)}"></script>')
    return "\n  ".join(extras)


def read_navbar(doc_dir: Path) -> str:
    """Read the navbar.html and extract the nav content for the left rail."""
    navbar_path = doc_dir / "navbar.html"
    if not navbar_path.exists():
        return '<div class="nav"><p>Navigation unavailable</p></div>'

    content = navbar_path.read_text(encoding="utf-8")
    # Extract the <div class="navframe"><nav class="nav">...</nav></div>
    m = re.search(r'<nav\s+class="nav">(.*?)</nav>', content, re.DOTALL)
    if m:
        return f'<nav class="nav">{m.group(1)}</nav>'

    return '<nav class="nav"><p>Navigation</p></nav>'


def apply_template(template: str, title: str, root: str,
                   head_extra: str, nav_content: str,
                   main_content: str) -> str:
    """Fill the shell template with extracted content."""
    result = template
    result = result.replace("{{TITLE}}", title)
    result = result.replace("{{ROOT}}", root)
    result = result.replace("{{HEAD_EXTRA}}", head_extra)
    result = result.replace("{{NAV_CONTENT}}", nav_content)
    result = result.replace("{{MAIN_CONTENT}}", main_content)
    return result


def process_file(filepath: Path, doc_dir: Path, template: str,
                 nav_content: str, landing_content: str | None) -> bool:
    """Process a single HTML file. Returns True if processed."""
    filename = filepath.name

    # Skip non-HTML and excluded files
    if not filename.endswith(".html"):
        return False
    if filename in SKIP_FILES:
        return False

    html = filepath.read_text(encoding="utf-8")

    # Don't re-process files that already have the shell
    if "site-header" in html:
        return False

    title = extract_title(html)
    root = compute_root(filepath, doc_dir)
    head_extra = extract_head_extras(html)

    # For index.html, use landing page content if available
    if filename == "index.html" and filepath.parent == doc_dir and landing_content:
        main_content = landing_content
    else:
        main_content = extract_main(html)

    # For standalone files, use minimal nav
    if filename in STANDALONE_FILES:
        nav = '<nav class="nav"><div class="nav_link"><a href="./">Home</a></div></nav>'
    else:
        # Adjust nav links to be relative to this file's depth
        nav = nav_content
        if root != "./":
            # Rewrite relative links in nav to account for depth
            nav = nav.replace('href="./', f'href="{root}')
            nav = nav.replace('data-path="./', f'data-path="{root}')

    result = apply_template(template, title, root, head_extra, nav, main_content)
    filepath.write_text(result, encoding="utf-8")
    return True


def main():
    parser = argparse.ArgumentParser(
        description="Apply Panta Rhei shell to doc-gen4 HTML output"
    )
    parser.add_argument(
        "--doc-dir", default="_site",
        help="Path to doc output directory (default: _site)"
    )
    parser.add_argument(
        "--template", default="scripts/shell_template.html",
        help="Path to shell template file"
    )
    parser.add_argument(
        "--landing", default="scripts/landing_page.html",
        help="Path to landing page content file"
    )
    args = parser.parse_args()

    doc_dir = Path(args.doc_dir).resolve()
    template_path = Path(args.template).resolve()
    landing_path = Path(args.landing).resolve()

    if not doc_dir.exists():
        print(f"ERROR: Doc directory not found: {doc_dir}")
        raise SystemExit(1)

    if not template_path.exists():
        print(f"ERROR: Template not found: {template_path}")
        raise SystemExit(1)

    template = template_path.read_text(encoding="utf-8")

    # Read landing page content
    landing_content = None
    if landing_path.exists():
        landing_content = landing_path.read_text(encoding="utf-8")

    # Read navbar once (shared across all pages)
    nav_content = read_navbar(doc_dir)

    # Copy shell assets
    assets_dir = doc_dir / "assets"
    assets_dir.mkdir(exist_ok=True)

    # Copy favicon if it exists in scripts/
    favicon_src = Path(args.template).parent / ".." / "scripts" / "favicon.svg"
    # We'll create the favicon inline instead

    # Create favicon.svg in assets/
    favicon_path = assets_dir / "favicon.svg"
    if not favicon_path.exists():
        favicon_path.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">'
            '<rect width="32" height="32" rx="6" fill="#f6f7f3"/>'
            '<text x="16" y="22" text-anchor="middle" '
            'font-family="Georgia,serif" font-size="14" font-weight="700" '
            'fill="#294b66">τL</text></svg>',
            encoding="utf-8"
        )

    # Process all HTML files
    print("=" * 60)
    print("Applying Panta Rhei shell")
    print("=" * 60)
    print(f"Doc dir:   {doc_dir}")
    print(f"Template:  {template_path}")
    print()

    processed = 0
    skipped = 0

    for filepath in sorted(doc_dir.rglob("*.html")):
        rel = filepath.relative_to(doc_dir)
        if process_file(filepath, doc_dir, template, nav_content, landing_content):
            processed += 1
            if processed <= 10 or processed % 50 == 0:
                print(f"  Wrapped: {rel}")
        else:
            skipped += 1

    print()
    print("=" * 60)
    print(f"Shell applied: {processed} pages wrapped, {skipped} skipped")
    print("=" * 60)


if __name__ == "__main__":
    main()
