#!/usr/bin/env python3
"""Filter doc-gen4 output to retain only TauLib content.

Doc-gen4 always generates documentation for all transitive dependencies
(Lean, Init, Std, Mathlib, Aesop, Batteries, etc.). This script strips
everything except TauLib, producing a clean, focused documentation site.

IMPORTANT: In CI, this script runs on a COPY of the doc output (_site/),
not on the cached docbuild/.lake/build/doc/ directory. This preserves
the cache for future runs — doc-gen4's index step needs all files intact.

What it does:
  1. Deletes 12 non-TauLib directories and their root HTML files
  2. Rebuilds navbar.html to show only TauLib modules
  3. Filters declaration-data.bmp to contain only TauLib declarations
  4. Creates TauLib.html redirect if missing
  5. Validates output and reports before/after statistics

Usage:
    python3 filter_docs.py --doc-dir _site              # CI (on copy)
    python3 filter_docs.py --doc-dir docbuild/.lake/build/doc  # local

All links in the output remain relative — hosting-agnostic.
"""

import json
import os
import re
import shutil
import argparse
from pathlib import Path


# Directories generated by doc-gen4 for transitive dependencies.
# These are always created and cannot be suppressed via doc-gen4 flags.
NON_TAULIB_DIRS = [
    "Aesop", "Batteries", "ImportGraph", "Init", "Lake", "Lean",
    "LeanSearchClient", "Mathlib", "Plausible", "ProofWidgets", "Qq", "Std",
]

# Root-level HTML pages for those dependencies (e.g., Aesop.html, Init.html)
NON_TAULIB_ROOT_PAGES = [f"{d}.html" for d in NON_TAULIB_DIRS]

# Additional root-level pages that reference only non-TauLib content.
# Safe to delete because the CI workflow now copies doc output to _site/
# before filtering — the docbuild cache stays pristine.
EXTRA_REMOVALS = [
    "foundational_types.html",   # References Lean core types (Init, Lean)
    "404.html",                  # Generic 404 page from doc-gen4
]


def count_html_files(directory: Path) -> int:
    """Count HTML files in a directory tree."""
    return sum(1 for _ in directory.rglob("*.html")) if directory.exists() else 0


def get_dir_size(directory: Path) -> int:
    """Get total size of a directory in bytes."""
    if not directory.exists():
        return 0
    return sum(f.stat().st_size for f in directory.rglob("*") if f.is_file())


def fmt_size(size_bytes: int) -> str:
    """Format bytes as human-readable size."""
    if size_bytes >= 1_000_000_000:
        return f"{size_bytes / 1_000_000_000:.1f} GB"
    if size_bytes >= 1_000_000:
        return f"{size_bytes / 1_000_000:.1f} MB"
    if size_bytes >= 1_000:
        return f"{size_bytes / 1_000:.1f} KB"
    return f"{size_bytes} B"


# ── Step 1: Delete non-TauLib directories and root pages ──────────────

def delete_non_taulib_content(doc_dir: Path) -> dict:
    """Remove all non-TauLib directories and root HTML pages.

    Returns dict with deletion statistics.
    """
    stats = {"dirs_deleted": 0, "files_deleted": 0, "bytes_freed": 0}

    # Delete directories
    for dirname in NON_TAULIB_DIRS:
        dirpath = doc_dir / dirname
        if dirpath.exists() and dirpath.is_dir():
            size = get_dir_size(dirpath)
            shutil.rmtree(dirpath)
            stats["dirs_deleted"] += 1
            stats["bytes_freed"] += size
            print(f"  Deleted {dirname}/ ({fmt_size(size)})")

    # Delete root HTML pages and their companion .hash/.trace files
    for filename in NON_TAULIB_ROOT_PAGES + EXTRA_REMOVALS:
        for ext in ["", ".hash", ".trace"]:
            filepath = doc_dir / (filename + ext)
            if filepath.exists():
                size = filepath.stat().st_size
                filepath.unlink()
                stats["files_deleted"] += 1
                stats["bytes_freed"] += size
                if not ext:
                    print(f"  Deleted {filename} ({fmt_size(size)})")

    return stats


# ── Step 2: Rebuild navbar.html ───────────────────────────────────────

def rebuild_navbar(doc_dir: Path) -> bool:
    """Rebuild navbar.html to contain only TauLib modules.

    Parses the existing navbar, extracts the TauLib <details> section,
    and rewrites the file with only that section plus the index link.

    Returns True on success, False on failure.
    """
    navbar_path = doc_dir / "navbar.html"
    if not navbar_path.exists():
        print("  WARNING: navbar.html not found, skipping")
        return False

    content = navbar_path.read_text(encoding="utf-8")

    # Strategy: extract the TauLib <details> section.
    # The navbar structure is:
    #   <div class="module_list">
    #     <details class="nav_sect" data-path="./Aesop.html">...</details>
    #     <details class="nav_sect" data-path="./Batteries.html">...</details>
    #     ...
    #     <details class="nav_sect" data-path="./TauLib.html">...</details>
    #   </div>
    #
    # We need to extract exactly the TauLib <details> block.

    # Find the TauLib section start
    taulib_marker = 'data-path="./TauLib.html"'
    taulib_start = content.find(taulib_marker)
    if taulib_start == -1:
        print("  WARNING: TauLib section not found in navbar.html")
        return False

    # Walk backwards to find the opening <details> tag
    details_open = content.rfind("<details", 0, taulib_start)
    if details_open == -1:
        print("  WARNING: Could not find <details> tag for TauLib section")
        return False

    # Find the matching closing </details> at the correct nesting depth.
    # We need to count nested <details> tags to find the right closing tag.
    pos = taulib_start
    depth = 1  # We're inside one <details>
    while depth > 0 and pos < len(content):
        next_open = content.find("<details", pos + 1)
        next_close = content.find("</details>", pos + 1)

        if next_close == -1:
            break  # Malformed HTML; bail out

        if next_open != -1 and next_open < next_close:
            depth += 1
            pos = next_open
        else:
            depth -= 1
            pos = next_close

    if depth != 0:
        print("  WARNING: Could not find matching </details> for TauLib section")
        return False

    taulib_end = pos + len("</details>")
    taulib_section = content[details_open:taulib_end]

    # Mark the TauLib section as open by default (so sidebar starts expanded)
    taulib_section = taulib_section.replace(
        '<details class="nav_sect" data-path="./TauLib.html"',
        '<details open class="nav_sect" data-path="./TauLib.html"',
        1
    )

    # Extract the <head> section from the original (contains CSS/JS links)
    head_match = re.search(r'<head>.*?</head>', content, re.DOTALL)
    head_section = head_match.group(0) if head_match else (
        '<head><meta charset="UTF-8"></meta>'
        '<meta name="viewport" content="width=device-width, initial-scale=1"></meta>'
        '<link rel="stylesheet" href="./style.css"></link>'
        '<script type="module" src="./nav.js"></script>'
        '<script type="module" src="./color-scheme.js"></script>'
        '<base target="_parent"></base></head>'
    )

    # Build the new navbar
    new_navbar = f"""<html lang="en">{head_section}<body><div class="navframe"><nav class="nav"><h3>General documentation</h3><div class="nav_link"><a href="./">index</a></div><div class="nav_link"><a href="./stats.html">statistics</a></div><div class="nav_link"><a href="./depgraph.html">dependency graph</a></div><h3>Library</h3><div class="module_list">{taulib_section}</div></nav></div></body></html>"""

    navbar_path.write_text(new_navbar, encoding="utf-8")

    old_size = len(content.encode("utf-8"))
    new_size = len(new_navbar.encode("utf-8"))
    print(f"  Rebuilt navbar.html: {fmt_size(old_size)} → {fmt_size(new_size)} "
          f"({100 - new_size / old_size * 100:.0f}% reduction)")

    return True


# ── Step 3: Filter declaration search index ───────────────────────────

def filter_declarations(doc_dir: Path) -> dict:
    """Filter declaration-data.bmp to contain only TauLib declarations.

    Despite the .bmp extension, this file is plain JSON containing all
    declarations from all transitive dependencies. We filter to keep only
    entries whose docLink starts with './TauLib'.

    Returns dict with filtering statistics.
    """
    data_path = doc_dir / "declarations" / "declaration-data.bmp"
    if not data_path.exists():
        print("  WARNING: declaration-data.bmp not found, skipping")
        return {"before": 0, "after": 0}

    old_size = data_path.stat().st_size

    try:
        with open(data_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        print(f"  WARNING: Could not parse declaration-data.bmp: {e}")
        return {"before": 0, "after": 0}

    stats = {"before": 0, "after": 0}

    # Filter declarations
    if "declarations" in data and isinstance(data["declarations"], dict):
        stats["before"] = len(data["declarations"])
        data["declarations"] = {
            name: info for name, info in data["declarations"].items()
            if info.get("docLink", "").startswith("./TauLib")
        }
        stats["after"] = len(data["declarations"])

    # Filter instances (if present)
    if "instances" in data and isinstance(data["instances"], dict):
        data["instances"] = {
            name: targets for name, targets in data["instances"].items()
            if any(
                isinstance(t, dict) and t.get("docLink", "").startswith("./TauLib")
                for t in (targets if isinstance(targets, list) else [targets])
            )
        }

    # Write back
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump(data, f, separators=(",", ":"))  # Compact JSON

    new_size = data_path.stat().st_size
    print(f"  Filtered declarations: {stats['before']:,} → {stats['after']:,} "
          f"({100 - stats['after'] / max(stats['before'], 1) * 100:.0f}% removed)")
    print(f"  File size: {fmt_size(old_size)} → {fmt_size(new_size)} "
          f"({100 - new_size / max(old_size, 1) * 100:.0f}% reduction)")

    # Also update the hash file if it exists (invalidate cache)
    hash_path = data_path.with_suffix(".bmp.hash")
    if hash_path.exists():
        hash_path.write_text("filtered", encoding="utf-8")

    return stats


# ── Step 4: Create missing root page ──────────────────────────────────

def create_root_page(doc_dir: Path) -> bool:
    """Create TauLib.html if it doesn't exist.

    Doc-gen4 creates a navbar link to ./TauLib.html but may not generate
    the page itself. We create a redirect to the landing page.
    """
    root_page = doc_dir / "TauLib.html"
    if root_page.exists():
        print("  TauLib.html already exists")
        return True

    # Build a page that redirects to index.html
    html = """<html lang="en"><head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="0; url=index.html">
<title>TauLib</title>
</head><body>
<p>Redirecting to <a href="index.html">TauLib documentation</a>...</p>
</body></html>"""

    root_page.write_text(html, encoding="utf-8")
    print("  Created TauLib.html (redirect to index.html)")
    return True


# ── Step 5: Validate output ──────────────────────────────────────────

def validate_output(doc_dir: Path) -> bool:
    """Run basic validation on the filtered output."""
    ok = True

    # Check TauLib directory exists
    taulib_dir = doc_dir / "TauLib"
    if not taulib_dir.exists():
        print("  ERROR: TauLib/ directory missing!")
        ok = False
    else:
        n_files = count_html_files(taulib_dir)
        print(f"  TauLib/ contains {n_files} HTML files")

    # Check no non-TauLib directories remain
    for dirname in NON_TAULIB_DIRS:
        if (doc_dir / dirname).exists():
            print(f"  ERROR: {dirname}/ was not deleted!")
            ok = False

    # Check navbar exists and is small
    navbar = doc_dir / "navbar.html"
    if navbar.exists():
        size = navbar.stat().st_size
        if size > 200_000:  # Should be well under 200 KB after filtering
            print(f"  WARNING: navbar.html is {fmt_size(size)} — may not be filtered")
    else:
        print("  WARNING: navbar.html missing")

    # Check critical files exist
    for fname in ["index.html", "style.css", "search.html", "search.js",
                   "declaration-data.js", "stats.html", "depgraph.html"]:
        if not (doc_dir / fname).exists():
            print(f"  WARNING: {fname} missing")

    # Sample a few TauLib pages to verify they exist
    sample_pages = [
        "TauLib/BookI/Kernel/Signature.html",
        "TauLib/BookII/CentralTheorem/CentralTheorem.html",
        "TauLib/BookIV/Electroweak/EWSynthesis.html",
        "TauLib/BookV/Cosmology/CMBSpectrum.html",
        "TauLib/BookVII/Meta/Saturation.html",
        "TauLib/Tour/Foundations.html",
    ]
    for page in sample_pages:
        if (doc_dir / page).exists():
            print(f"  OK: {page}")
        else:
            print(f"  WARNING: {page} not found")

    return ok


# ── Main ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Filter doc-gen4 output to retain only TauLib content"
    )
    parser.add_argument(
        "--doc-dir",
        default="docbuild/.lake/build/doc",
        help="Path to doc-gen4 output directory (default: docbuild/.lake/build/doc)"
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be done without making changes"
    )
    args = parser.parse_args()

    doc_dir = Path(args.doc_dir).resolve()

    if not doc_dir.exists():
        print(f"ERROR: Doc directory not found: {doc_dir}")
        raise SystemExit(1)

    if not (doc_dir / "TauLib").exists():
        print(f"ERROR: TauLib/ not found in {doc_dir} — is this a doc-gen4 output?")
        raise SystemExit(1)

    # Compute before stats
    total_before = get_dir_size(doc_dir)
    html_before = sum(1 for _ in doc_dir.rglob("*.html"))

    print("=" * 60)
    print("TauLib Doc-Gen4 Filter")
    print("=" * 60)
    print(f"Input:  {doc_dir}")
    print(f"Before: {fmt_size(total_before)}, {html_before} HTML files")
    print()

    if args.dry_run:
        print("DRY RUN — no changes will be made")
        print()
        for dirname in NON_TAULIB_DIRS:
            dirpath = doc_dir / dirname
            if dirpath.exists():
                size = get_dir_size(dirpath)
                print(f"  Would delete {dirname}/ ({fmt_size(size)})")
        return

    # Step 1: Delete non-TauLib content
    print("--- Step 1: Deleting non-TauLib directories ---")
    del_stats = delete_non_taulib_content(doc_dir)
    print(f"  Total: {del_stats['dirs_deleted']} dirs, "
          f"{del_stats['files_deleted']} files, "
          f"{fmt_size(del_stats['bytes_freed'])} freed")
    print()

    # Step 2: Rebuild navbar
    print("--- Step 2: Rebuilding navbar ---")
    rebuild_navbar(doc_dir)
    print()

    # Step 3: Filter declarations
    print("--- Step 3: Filtering search index ---")
    decl_stats = filter_declarations(doc_dir)
    print()

    # Step 4: Create missing root page
    print("--- Step 4: Creating root page ---")
    create_root_page(doc_dir)
    print()

    # Step 5: Validate
    print("--- Step 5: Validating output ---")
    valid = validate_output(doc_dir)
    print()

    # Summary
    total_after = get_dir_size(doc_dir)
    html_after = sum(1 for _ in doc_dir.rglob("*.html"))
    reduction = 100 - total_after / max(total_before, 1) * 100

    print("=" * 60)
    print("Filter complete")
    print("=" * 60)
    print(f"Size:         {fmt_size(total_before)} → {fmt_size(total_after)} "
          f"({reduction:.0f}% reduction)")
    print(f"HTML files:   {html_before} → {html_after}")
    print(f"Declarations: {decl_stats['before']:,} → {decl_stats['after']:,}")
    print(f"Validation:   {'PASSED' if valid else 'WARNINGS (see above)'}")
    print()
    print("All links are relative — serve from any static host.")


if __name__ == "__main__":
    main()
